#!/usr/bin/env bash

##	(c)2019 Colin Vanden Heuvel. All rights reserved.
##	
##	For the exclusive use of the University of Wisconsin - Madison

##
##	DO NOT EDIT THIS FILE UNLESS INSTRUCTED TO DO SO
##


if [ "$1" == "clean" ]; then
	rm -f problem1 problem2 problem2.o problem3
	exit 0
fi


module load gcc/recommended
if [ -f problem1.c ]; then
	$CC -O3 -fopenmp -std=c11 -lm -lgomp problem1.c -o problem1
elif [ -f problem1.cpp ]; then
	$CXX -O3 -fopenmp -std=c++17 -lm -lgomp problem1.cpp -o problem1
fi
module unload gcc/recommended

module load pgi/18.10
if [ -f problem2.c ]; then
	$CC -fast -O3 -ta=tesla:managed,ccall -Minfo=accel -c11 -lm problem2.c -o problem2
elif [ -f problem2.cpp ]; then
	$CXX -fast -O3 -ta=tesla:managed,ccall -Minfo=accel -std=c++17 -lm problem2.cpp -o problem2
fi
module unload pgi/18.10

module load cuda/10.0
nvcc problem3.cu -ccbin $CU_CCBIN --std c++14 -lm -o problem3
module unload cuda/10.0

